/**:
  ros__parameters:
    origin.latitude: 40.246562
    origin.longitude: -111.647649
    origin.altitude: 1486.0

    water_salinity_ppt: 0.0
    fluid_pressure_atm: 87250.0
    holoocean_vehicle: "auv0"
    frost_vehicle: "coug0"

coug0:
  pressure_converter:
    ros__parameters:
      fluid_density: 1025.0
      fluid_pressure_atm: 87250.0
      odometry_topic: '/holoocean/auv0/DepthSensor'
      pressure_topic: 'pressure/data'



  ucommand_bridge:
    ros__parameters:
      fin_scalar: -3.0
      publish_thruster: false

  dvl_converter_node:
    ros__parameters:
      vel_topic: "/holoocean/auv0/DVLSensorVelocity"
      range_topic: "/holoocean/auv0/DVLSensorRange"
      output_topic: "dvl/data"
      beam_elevation_deg: [20.0, 20.0, 20.0, 20.0]  # [deg] 
      beam_azimuth_deg: [45.0, 135.0, 225.0, 315.0]  # [deg] 

      # noise_sigmas: [0.02, 0.02, 0.02] # [m/s] DVL body-velocity uncertainty sigmas.